### ISSUE TITLE
[10%] Complete the function: Intelligent analysis

### ISSUE THREAD

**Issue by TonyLiangJunsheng** [CCPX-system/CCPX-engine#2]

**Comment by fjw2015** [comment]
## Post request:

`URL`: localhost:8080/seller/intelligentAnalysis?sellerId=5&startTime=2016/11/14 00:00:00&endTime=2016/11/14 00:00:00&tradeType=0
`Paras`: sellerId, startTime, endTime, tradeType(0 or 1)

## Response:

`errno`, `err`, `4diagrams data`
{
  "topDiffIndustry": {
    "yAxisTitleText": "trade points",
    "seriesData": [
      ["BANK OF CHINA",70 ],
      ["McDonald's",50]
    ]
  },
  "topSameIndustry": {
    "yAxisTitleText": "trade points",
    "seriesData": [
      [ "CATHAY PACIFIC",310 ],
      ["CHINA SOUTHERN AIRLINES",50]
    ]
  },
  "industryRatio": {
    "seriesData": [
      ["Travel",0.75],
      ["Restaurant", 0.1 ],
      ["Services",0.15]
    ],
    "titleText": "trade points"
  },
  "timeSequence": {
    "xAxisCategories": [
      "2016/11/07 00:10:00",
      "2016/11/07 00:20:00",
      "2016/11/07 00:30:00",
      "2016/11/07 00:40:00"
    ],
    "yAxisTitleText": "trade points",
    "seriesData": [
      40,
      165,
      20,
      50
    ]
  },
  "err": null,
  "errno": 0
}

**Comment by fjw2015** [comment]
Post request:
---
`URL`: localhost:8080/seller/intelligentAnalysis?sellerId=5&startTime=2016/11/14 00:00:00&endTime=2016/11/14 00:00:00&tradeType=0
`Paras`: sellerId, startTime, endTime, tradeType(0 or 1)
Response:
---
`errno`, `err`, `4diagrams data`
{
  "topDiffIndustry": {
    "yAxisTitleText": "trade points",
    "seriesData": [
      ["BANK OF CHINA",70 ],
      ["McDonald's",50]
    ]
  },
  "topSameIndustry": {
    "yAxisTitleText": "trade points",
    "seriesData": [
      [ "CATHAY PACIFIC",310 ],
      ["CHINA SOUTHERN AIRLINES",50]
    ]
  },
  "industryRatio": {
    "seriesData": [
      ["Travel",0.75],
      ["Restaurant", 0.1 ],
      ["Services",0.15]
    ],
    "titleText": "trade points"
  },
  "timeSequence": {
    "xAxisCategories": [
      "2016/11/07 00:10:00",
      "2016/11/07 00:20:00",
      "2016/11/07 00:30:00",
      "2016/11/07 00:40:00"
    ],
    "yAxisTitleText": "trade points",
    "seriesData": [
      40,
      165,
      20,
      50
    ]
  },
  "err": null,
  "errno": 0
}

**Comment by fjw2015** [comment]
Post request:
---
`URL`: localhost:8080/seller/intelligentAnalysis?sellerId=5&startTime=2016/11/14 00:00:00&endTime=2016/11/14 00:00:00&tradeType=0
`Paras`: sellerId, startTime, endTime, tradeType(0 or 1)
Response:
---
`errno`, `err`, `4diagrams data`
{
  "topDiffIndustry": {
    "yAxisTitleText": "trade points",
    "seriesData": [
      ["BANK OF CHINA",70 ],
      ["McDonald's",50]
    ]
  },
  "topSameIndustry": {
    "yAxisTitleText": "trade points",
    "seriesData": [
      [ "CATHAY PACIFIC",310 ],
      ["CHINA SOUTHERN AIRLINES",50]
    ]
  },
  "industryRatio": {
    "seriesData": [
      ["Travel",0.75],
      ["Restaurant", 0.1 ],
      ["Services",0.15]
    ],
    "titleText": "trade points"
  },
  "timeSequence": {
    "xAxisCategories": [
      "2016/11/07 00:10:00",
      "2016/11/07 00:20:00",
      "2016/11/07 00:30:00",
      "2016/11/07 00:40:00"
    ],
    "yAxisTitleText": "trade points",
    "seriesData": [
      40,
      165,
      20,
      50
    ]
  },
  "err": null,
  "errno": 0
}

**Comment by fjw2015** [comment]
Post request:
---
`URL`: localhost:8080/seller/intelligentAnalysis?sellerId=5&startTime=2016/11/14 00:00:00&endTime=2016/11/14 00:00:00&tradeType=0
`Paras`: sellerId, startTime, endTime, tradeType(0 or 1)
Response:
---
`errno`, `err`, `4diagrams data`
{
  "topDiffIndustry": {
    "yAxisTitleText": "trade points",
    "seriesData": [
      ["BANK OF CHINA",70 ],
      ["McDonald's",50]
    ]
  },
  "topSameIndustry": {
    "yAxisTitleText": "trade points",
    "seriesData": [
      [ "CATHAY PACIFIC",310 ],
      ["CHINA SOUTHERN AIRLINES",50]
    ]
  },
  "industryRatio": {
    "seriesData": [
      ["Travel",0.75],
      ["Restaurant", 0.1 ],
      ["Services",0.15]
    ],
    "titleText": "trade points"
  },
  "timeSequence": {
    "xAxisCategories": [
      "2016/11/07 00:10:00",
      "2016/11/07 00:20:00",
      "2016/11/07 00:30:00",
      "2016/11/07 00:40:00"
    ],
    "yAxisTitleText": "trade points",
    "seriesData": [
      40,
      165,
      20,
      50
    ]
  },
  "err": null,
  "errno": 0
}

**Comment by fjw2015** [comment]
Post request:
---
`URL`: localhost:8080/seller/intelligentAnalysis?sellerId=5&startTime=2016/11/14 00:00:00&endTime=2016/11/14 00:00:00&tradeType=0
`Paras`: sellerId, startTime, endTime, tradeType(0 or 1)
Response:
---
`errno`, `err`, `4diagrams data`
{
  "topDiffIndustry": {
    "yAxisTitleText": "trade points",
    "seriesData": [
      ["BANK OF CHINA",70 ],
      ["McDonald's",50]
    ]
  },
  "topSameIndustry": {
    "yAxisTitleText": "trade points",
    "seriesData": [
      [ "CATHAY PACIFIC",310 ],
      ["CHINA SOUTHERN AIRLINES",50]
    ]
  },
  "industryRatio": {
    "seriesData": [
      ["Travel",0.75],
      ["Restaurant", 0.1 ],
      ["Services",0.15]
    ],
    "titleText": "trade points"
  },
  "timeSequence": {
    "xAxisCategories": [
      "2016/11/07 00:10:00",
      "2016/11/07 00:20:00",
      "2016/11/07 00:30:00",
      "2016/11/07 00:40:00"
    ],
    "yAxisTitleText": "trade points",
    "seriesData": [
      40,
      165,
      20,
      50
    ]
  },
  "err": null,
  "errno": 0
}
